version: '2.1'

services:
  db:
    image: mariadb:latest
    container_name: sliboot_db_container
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    logging:       
      driver:   "json-file"
      options:  
        max-size: "30m"
        max-file: "5"
  
      
  sliboot:
    image: onap/ccsdk-sliboot-alpine-image:latest
    depends_on:
      - db
    container_name: sliboot_sli_container
    ports:
      - "8080:8080"
      - "8443:8443"
    links:
      - db:dbhost
    environment:
      - MYSQL_DB_HOST=dbhost
      - MYSQL_DB_USER=${MYSQL_USER}
      - MYSQL_DB_PASSWD=${MYSQL_PASSWORD}
      - MYSQL_DB_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - SDNC_CONFIG_DIR=/opt/onap/ccsdk/config
    logging:       
      driver:   "json-file"
      options:  
        max-size: "30m"
        max-file: "5"
    extra_hosts:
      aaf-onap-test.osaaf.org: 10.12.5.145


