--liquibase formatted sql
--changeset message_table:18_10.create_message_table.sql

CREATE TABLE NELGEN_MESSAGE (NELGEN_MESSAGE_ID  VARCHAR(500) PRIMARY KEY, 
MESSAGE_ID VARCHAR(500) COMMENT 'Message id', 
CONVERSATION_ID  VARCHAR(500) COMMENT 'Conversation id for the transaction',
SERVICE_NAME VARCHAR(100) COMMENT 'Service name',
START_TIME DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Transaction start time', 
ELAPSED_MILLIS INTEGER ,
STATUS VARCHAR(20) COMMENT 'Transaction status', 
REQUEST LONGTEXT NOT NULL COMMENT 'Request JSON',
RESPONSE LONGTEXT COMMENT 'Request JSON', 
REQUESTER VARCHAR(50) COMMENT 'Requester'
);
