version: '2.1'

services:
  nengdb:
     image: mariadb:10.5
     container_name: nengdb
     ports:
       - "${NENG_DB_PORT}:3306"
     #volumes:
     #  - /var/lib/nengdb:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: "${NENG_DB_ROOT}"
       MYSQL_DATABASE: neng
       MYSQL_USER: "${NENG_DB_USER}"
       MYSQL_PASSWORD: "${NENG_DB_PASS}"

  neng:
     depends_on :
       - nengdb
     image: onap/ccsdk-apps-ms-neng:latest
     container_name: neng
     ports:
       - "${NENG_SERV_PORT}:8080"
     restart: always
     links:
       - nengdb:mariadb-galera 
     environment:
       SPRING_PROFILE: "${SPRING_PROFILE}"
       NENG_DB_URL: "jdbc:mysql://mariadb-galera:3306/neng"
       NENG_DB_USER: "${NENG_DB_USER}"
       NENG_DB_PASS: "${NENG_DB_PASS}"
       POL_CLIENT_AUTH: "${POL_CLIENT_AUTH}"
       POL_BASIC_AUTH_USER: "${POL_BASIC_AUTH_USER}"
       POL_BASIC_AUTH_PASSWORD: "${POL_BASIC_AUTH_PASSWORD}"
       POL_URL: "${POL_URL}"
       POL_ENV: "${POL_ENV}"
       POL_REQ_ID: "${POL_REQ_ID}"
       AAI_CERT_PASS: "${AAI_CERT_PASS}"
       AAI_CERT_PATH: "${AAI_CERT_PATH}"
       AAI_URI: "${AAI_URI}"
       AAI_AUTH: "${AAI_AUTH}"
       DISABLE_HOST_VERIFICATION: "${DISABLE_HOST_VERIFICATION:-false}"



