package org.onap.ccsdk.apps.cdssdclistener;

import java.util.List;
import org.onap.sdc.api.consumer.INotificationCallback;
import org.onap.sdc.api.notification.IArtifactInfo;
import org.onap.sdc.api.notification.INotificationData;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

@Component
public class CdsSdcListenerNotificationCallback implements INotificationCallback {

    private static Logger LOG = LoggerFactory.getLogger(CdsSdcListenerNotificationCallback.class);

    @Override
    public void activateCallback(INotificationData notificationData) {
        LOG.info(notificationData.getDistributionID(), "The UUID generated by SDC {}");
        processNotification(notificationData);
    }

    private void processNotification(INotificationData notificationData) {
        downloadTheArtifact(notificationData.getServiceArtifacts(), notificationData.getDistributionID());
    }

    /**
     * Download the TOSCA CSAR artifact.
     * @param artifactInfo - An object consists of Artifact information.
     * @param distributionId - Generated UUID.
     */
    private void downloadTheArtifact(List<IArtifactInfo> artifactInfo, String distributionId) {

    }
}
